##
# Tiger compiler
#
# @file
# @version 0.1


all: tiger

tiger:
	java -Xmx500M -cp "/home/delmerico/cs8803/antlr-4.11.1-complete.jar:$CLASSPATH" org.antlr.v4.Tool -Dlanguage=Cpp -o antlr Tiger.g4


# end
